### ISSUE TITLE
About the test results

### ISSUE THREAD

**Issue by positive-measure** [WoojungBae/afttest#1]
In my experiments, the p-values were very large whether I tested on heteroscedastic or homoskedastic data.
In addition,the example "afttest" in manual returns p-value 0.5,but it is homoskedastic.

**Comment by WoojungBae** [comment]
Thank you for sharing an issue. I am checking on it. I will get back to you soon.

**Comment by WoojungBae** [comment]
> In my experiments, the p-values were very large whether I tested on heteroscedastic or homoskedastic data. In addition,the example "afttest" in manual returns p-value 0.5,but it is homoskedastic.

I now updated the source code and updated it on CRAN. Please let me know if you still have the same problem.
